### ISSUE TITLE
Object-conditional generation

### ISSUE THREAD

**Issue by On-JungWoan** [jyunlee/InterHandGen#4]
Hi, @jyunlee! Thank you for sharing your code. I'm trying to use the ARCTIC dataset for your code, and have some questions.

- How can you get the object point cloud? (I mean, how can you generate the object point cloud?)
- Do you have any plans to release the code regarding Object-conditional generation?

**Comment by jyunlee** [comment]
Hello! 😃 Thank you for your continued interest in our work, and I apologize for the late reply due to other workloads I’ve recently had.

The input object point cloud was created via sampling 2048 points from the surface of an ARCTIC object mesh. More specifically, I used `sample.sample_surface_even` function from `trimesh` library. 

My original plan was to release only the main code of InterHandGen, which performs two-hand generation. The extension for object-conditional generation would be quite straightforward (i.e., adding an object feature as an additional token to the encoder), but please feel free to reach out to me if you need more discussions!

**Comment by On-JungWoan** [comment]
Thanks for your response!
